/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SubmissionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'reviewed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const SocialLinks = IDL.Record({
  'soundcloud' : IDL.Opt(IDL.Text),
  'instagram' : IDL.Opt(IDL.Text),
  'spotify' : IDL.Opt(IDL.Text),
  'youtube' : IDL.Opt(IDL.Text),
});
export const Int = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Submission = IDL.Record({
  'id' : IDL.Text,
  'status' : SubmissionStatus,
  'submitterName' : IDL.Opt(IDL.Text),
  'submitterRole' : IDL.Opt(IDL.Text),
  'socialLinks' : SocialLinks,
  'submittedAt' : Int,
  'specificGenre' : IDL.Opt(IDL.Text),
  'bandName' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'genre' : IDL.Text,
  'submitterEmail' : IDL.Opt(IDL.Text),
  'trackBlobs' : IDL.Vec(ExternalBlob),
  'epkBlob' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSubmission' : IDL.Func([IDL.Text], [], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSubmission' : IDL.Func([IDL.Text], [Submission], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBand' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        SocialLinks,
        IDL.Opt(ExternalBlob),
        IDL.Vec(ExternalBlob),
      ],
      [IDL.Text],
      [],
    ),
  'updateSubmissionStatus' : IDL.Func([IDL.Text, SubmissionStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SubmissionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'reviewed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const SocialLinks = IDL.Record({
    'soundcloud' : IDL.Opt(IDL.Text),
    'instagram' : IDL.Opt(IDL.Text),
    'spotify' : IDL.Opt(IDL.Text),
    'youtube' : IDL.Opt(IDL.Text),
  });
  const Int = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Submission = IDL.Record({
    'id' : IDL.Text,
    'status' : SubmissionStatus,
    'submitterName' : IDL.Opt(IDL.Text),
    'submitterRole' : IDL.Opt(IDL.Text),
    'socialLinks' : SocialLinks,
    'submittedAt' : Int,
    'specificGenre' : IDL.Opt(IDL.Text),
    'bandName' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'genre' : IDL.Text,
    'submitterEmail' : IDL.Opt(IDL.Text),
    'trackBlobs' : IDL.Vec(ExternalBlob),
    'epkBlob' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSubmission' : IDL.Func([IDL.Text], [], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSubmission' : IDL.Func([IDL.Text], [Submission], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBand' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          SocialLinks,
          IDL.Opt(ExternalBlob),
          IDL.Vec(ExternalBlob),
        ],
        [IDL.Text],
        [],
      ),
    'updateSubmissionStatus' : IDL.Func([IDL.Text, SubmissionStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };