/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type Int = bigint;
export interface SocialLinks {
  'soundcloud' : [] | [string],
  'instagram' : [] | [string],
  'spotify' : [] | [string],
  'youtube' : [] | [string],
}
export interface Submission {
  'id' : string,
  'status' : SubmissionStatus,
  'submitterName' : [] | [string],
  'submitterRole' : [] | [string],
  'socialLinks' : SocialLinks,
  'submittedAt' : Int,
  'specificGenre' : [] | [string],
  'isArchived' : boolean,
  'bandName' : string,
  'website' : [] | [string],
  'genre' : string,
  'isFaved' : boolean,
  'submitterEmail' : [] | [string],
  'isShortlisted' : boolean,
  'trackBlobs' : Array<ExternalBlob>,
  'epkBlob' : [] | [ExternalBlob],
}
export type SubmissionLabel = { 'shortlisted' : null } |
  { 'archived' : null } |
  { 'faved' : null };
export type SubmissionStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'reviewed' : null } |
  { 'accepted' : null };
export type Tab = { 'newSubmissions' : null } |
  { 'shortlisted' : null } |
  { 'archived' : null } |
  { 'faved' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteSubmission' : ActorMethod<[string], undefined>,
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSubmission' : ActorMethod<[string], Submission>,
  'getSubmissionsByTab' : ActorMethod<[Tab], Array<Submission>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'labelSubmission' : ActorMethod<
    [string, SubmissionLabel, boolean],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBand' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      SocialLinks,
      [] | [ExternalBlob],
      Array<ExternalBlob>,
    ],
    string
  >,
  'updateSubmissionStatus' : ActorMethod<[string, SubmissionStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];